---
title: "ANOVAs pro Gui"
output:
  word_document: default
  pdf_document: default
---

por Francisko de Moraes Rezende, francisko.rezende@gmail.com, 2020-03-26

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 600)
```

```{r pacotes, message=FALSE}

# carregando os pacotes ---------------------------------------------------

lista_de_pacotes  <- c("tidyverse",
                       "readxl",
                       "here",
                       "lme4",
                       "janitor",
                       "ggbeeswarm",
                       "broom",
                       "tufte",
                       "ggthemes",
                       "ggpol")


pacotes_novos <-
  lista_de_pacotes[!(lista_de_pacotes %in% installed.packages()[, "Package"])]
if (length(pacotes_novos))
  install.packages(pacotes_novos)


library(tidyverse)
library(readxl)
library(here)
library(lme4)
library(janitor)
library(ggbeeswarm)
library(broom)
library(ggthemes)
library(ggpol)
```


# Carregando os dados



```{r carregando-dados, echo=FALSE}
mp <-
  readxl::read_xlsx(here::here("dados", "MP, UI e Angle - p Chikao.xlsx"),
                    sheet = "MP") %>% 
  janitor::clean_names()

ui <-
  readxl::read_xlsx(here::here("dados", "MP, UI e Angle - p Chikao.xlsx"),
                    sheet = "UI") %>% 
  janitor::clean_names() %>% 
  dplyr::mutate_at(.vars = vars(sp:rep), .funs = ~ factor(.))

angle <-
  readxl::read_xlsx(here::here("dados", "MP, UI e Angle - p Chikao.xlsx"),
                    sheet = "Angle") %>% 
  janitor::clean_names() %>% 
  dplyr::mutate_at(.vars = vars(sp:rep), .funs = ~ factor(.))
```


# ANOVA ui

## Código

```{r anova-ui, results='hide'}
ui_m1 <- lm(ui ~ sp * face, data = ui)

anova(ui_m1)

ui_m2 <- update(ui_m1, . ~ . -sp:face)

anova(ui_m2) %>% 
  rename(`P value` = `Pr(>F)`)
```

## Tabela ANOVA ui
```{r tabela-ui}
anova(ui_m2) %>% 
  rename(`P value` = `Pr(>F)`) %>% 
  knitr::kable(digits = 3)
```

## Gráfico

Os dois gráficos abaixo tem as mesmas informções, escolha o que mais lhe agradar.

```{r grafico-ui}
ui %>% 
  ggplot(aes(x = sp, y = ui)) +
  geom_boxplot() +
  geom_quasirandom(groupOnX = T,
                   alpha = .5) +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        text = element_text(size = 12)) 

ui %>% 
  ggplot(aes(x = sp, y = ui)) +
  geom_boxjitter(jitter.height = 0) +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        text = element_text(size = 12)) 
```



# ANOVA angle

## Código

```{r anova-angulo, results='hide'}
angle_m1 <- lm(angle ~ sp*face, data = angle)

anova(angle_m1)

angle_m2 <- update(angle_m1, . ~ . - sp:face)

anova(angle_m1, angle_m2)

anova(angle_m2)
```

## Tabela

```{r tabela-angulo, echo=FALSE}
anova(angle_m2) %>% 
  rename(`P value` = `Pr(>F)`) %>% 
  knitr::kable(digits = 3)
```


## Gráfico

Os dois gráficos abaixo tem as mesmas informções, escolha o que mais lhe agradar.

```{r grafico-angulo}
angle %>% 
  ggplot(aes(x = sp, y = angle)) +
  geom_boxplot() +
  geom_quasirandom(groupOnX = T,
                   alpha = .5) +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        text = element_text(size = 12)) 


angle %>% 
  ggplot(aes(x = sp, y = angle)) +
  geom_boxjitter(jitter.height = 0) +
  theme_classic() +
  theme(axis.line.x = element_blank(),
        text = element_text(size = 12)) 
```

